apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
---    
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled    