apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: appmesh-system
spec:
  releaseName: flagger
  chart:
    spec:
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: appmesh-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    meshProvider: appmesh:v1beta2
    metricsServer: http://appmesh-prometheus.appmesh-system.svc.cluster.local:9090